# To obtain a Flickr API key and shared secret:
# 1. Go to https://www.flickr.com/services/apps/create/apply
# 2. Click "Apply for a Non-Commercial Key" (or "Apply for a Commercial Key").
# 3. Enter a name and description for your app.
# 4. Copy the "Key" to flickr.apiKey and "Secret" to flickr.sharedSecret below.

flickr.apiKey=
flickr.sharedSecret=

org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.com.artware.flickr.sftp=debug
